import { FrameTheme, Sticker } from '../types';

export const FRAME_THEMES: FrameTheme[] = [
  {
    id: 'yellow_chick',
    name: '노랑 병아리반 🐣',
    icon: '🐣',
    bgColor: '#FEF08A',
    cardBg: '#FFFBEB',
    textColor: '#854D0E',
    accentColor: '#F59E0B',
    borderColor: '#FDE047',
    pattern: 'chicks',
    badge: '🐣 삐약삐약 병아리반',
  },
  {
    id: 'pink_bunny',
    name: '딸기 토끼반 🐰',
    icon: '🐰',
    bgColor: '#FECDD3',
    cardBg: '#FFF1F2',
    textColor: '#9F1239',
    accentColor: '#F43F5E',
    borderColor: '#FDA4AF',
    pattern: 'dots',
    badge: '🍓 달콤 토끼반',
  },
  {
    id: 'green_sprout',
    name: '파릇 새싹반 🌱',
    icon: '🌱',
    bgColor: '#BBF7D0',
    cardBg: '#F0FDF4',
    textColor: '#166534',
    accentColor: '#22C55E',
    borderColor: '#86EFAC',
    pattern: 'sprouts',
    badge: '🌿 쑥쑥 자라는 새싹반',
  },
  {
    id: 'blue_cloud',
    name: '무지개 구름반 🌈',
    icon: '🌈',
    bgColor: '#BAE6FD',
    cardBg: '#F0F9FF',
    textColor: '#075985',
    accentColor: '#0284C7',
    borderColor: '#7DD3FC',
    pattern: 'clouds',
    badge: '☁️ 맑고 푸른 구름반',
  },
  {
    id: 'bear_cozy',
    name: '도토리 곰돌반 🐻',
    icon: '🐻',
    bgColor: '#E7D5C2',
    cardBg: '#FAF5EF',
    textColor: '#78350F',
    accentColor: '#B45309',
    borderColor: '#D7B99B',
    pattern: 'dots',
    badge: '🌰 포근포근 곰돌반',
  },
  {
    id: 'purple_star',
    name: '반짝 별빛반 ⭐',
    icon: '⭐',
    bgColor: '#DDD6FE',
    cardBg: '#F5F3FF',
    textColor: '#5B21B6',
    accentColor: '#7C3AED',
    borderColor: '#C4B5FD',
    pattern: 'stars',
    badge: '✨ 반짝이는 별빛반',
  },
  {
    id: 'crayon_fun',
    name: '크레파스 미술반 🖍️',
    icon: '🖍️',
    bgColor: '#FED7AA',
    cardBg: '#FFF7ED',
    textColor: '#9A3412',
    accentColor: '#EA580C',
    borderColor: '#FDBA74',
    pattern: 'crayons',
    badge: '🎨 알록달록 그림반',
  },
  {
    id: 'classic_white',
    name: '클래식 화이트 🤍',
    icon: '🤍',
    bgColor: '#FFFFFF',
    cardBg: '#F8FAFC',
    textColor: '#1E293B',
    accentColor: '#64748B',
    borderColor: '#E2E8F0',
    pattern: 'minimal',
    badge: '📸 우리들의 소중한 순간',
  },
  {
    id: 'modern_dark',
    name: '모던 딥블랙 🖤',
    icon: '🖤',
    bgColor: '#18181B',
    cardBg: '#27272A',
    textColor: '#FAFAFA',
    accentColor: '#E4E4E7',
    borderColor: '#3F3F46',
    pattern: 'minimal',
    badge: '✨ Our Sweet Moments',
  }
];

export const POSE_PROMPTS = [
  { step: 1, title: '첫 번째 컷!', pose: '예쁜 꽃받침 포즈 🌸', tip: '턱 아래에 손을 모아 꽃받침을 해봐요!' },
  { step: 2, title: '두 번째 컷!', pose: '깜찍한 윙크와 브이 ✌️😉', tip: '한 눈을 감고 손가락으로 브이~!' },
  { step: 3, title: '세 번째 컷!', pose: '사랑해요 하트 뿅뿅 ❤️', tip: '머리 위로 큰 하트를 그려봐요!' },
  { step: 4, title: '네 번째 컷!', pose: '신나는 개구쟁이 표정 😝', tip: '볼에 바람을 빵빵하게 넣어봐요!' },
  { step: 5, title: '마지막 컷!', pose: '우리반 최고! 엄지 척! 👍', tip: '활짝 웃으며 최고 포즈를 지어요!' },
];

export const STICKERS: Sticker[] = [
  { id: 'chick', name: '병아리', emoji: '🐥', category: 'cute' },
  { id: 'heart', name: '하트', emoji: '💖', category: 'cute' },
  { id: 'sparkles', name: '반짝이', emoji: '✨', category: 'cute' },
  { id: 'sprout', name: '새싹', emoji: '🌱', category: 'cute' },
  { id: 'flower', name: '튤립', emoji: '🌷', category: 'cute' },
  { id: 'sunflower', name: '해바라기', emoji: '🌻', category: 'cute' },
  { id: 'rainbow', name: '무지개', emoji: '🌈', category: 'cute' },
  { id: 'bear', name: '곰돌이', emoji: '🧸', category: 'cute' },
  { id: 'bunny', name: '토끼', emoji: '🐰', category: 'cute' },
  { id: 'crown', name: '왕관', emoji: '👑', category: 'party' },
  { id: 'ribbon', name: '리본', emoji: '🎀', category: 'party' },
  { id: 'party', name: '파티폭죽', emoji: '🎉', category: 'party' },
  { id: 'balloon', name: '풍선', emoji: '🎈', category: 'party' },
  { id: 'candy', name: '사탕', emoji: '🍭', category: 'party' },
  { id: 'sunglasses', name: '선글라스', emoji: '🕶️', category: 'face' },
  { id: 'blush', name: '볼터치', emoji: '🌸', category: 'face' },
  { id: 'star_eyes', name: '반짝눈', emoji: '🤩', category: 'face' },
  { id: 'crayon', name: '크레파스', emoji: '🖍️', category: 'school' },
  { id: 'book', name: '책', emoji: '📖', category: 'school' },
  { id: 'clap', name: '박수', emoji: '👏', category: 'school' },
  { id: 'thumb', name: '최고', emoji: '👍', category: 'school' },
  { id: 'camera', name: '카메라', emoji: '📸', category: 'school' },
];

export const CLASS_NAME_PRESETS = [
  '햇살가득 햇님반 ☀️',
  '달콤 사랑 딸기반 🍓',
  '삐약삐약 병아리반 🐥',
  '파릇파릇 새싹반 🌱',
  '하늘하늘 구름반 ☁️',
  '알록달록 무지개반 🌈',
  '포근포근 곰돌이반 🐻',
  '반짝반짝 별빛반 ⭐',
  '지혜로운 숲속반 🌳',
  '행복가득 우리반 💕',
];

export const SLOGAN_PRESETS = [
  '우리들은 언제나 단짝친구! 💕',
  '웃음이 퐁퐁 솟아나는 날 🌈',
  '우리는 반짝이는 별처럼 빛나요 ⭐',
  '매일매일 행복한 우리 유치원 🏫',
  '사랑스런 우리들의 추억 찰칵! 📸',
  '쑥쑥 자라나는 귀여운 꿈나무 🌱',
];
